### ISSUE TITLE
ERC721 Factory Design

### ISSUE THREAD

**Issue by rykci** [filswan/nft#6]
Instead of having one collection for every user to mint to, we want each user to have their own collection(s).

Create MinterFactory contract
- `createMinter(name, symbol)` : deploy ERC721 contract (Minter.sol), transfer ownership to `msg.sender`
- has mapping (userAddress -> minterAddress[]) to store Minter instances

users can use the deployed Minters to mint NFTs, each instance/contract is its own NFT collection

Problems:
- Upgradeability
    - MinterFactory can be upgradeable.
    -  If Minter.sol is upgradeable, how can we apply upgrade to all instances?

**Comment by liushmh** [comment]
https://docs.opensea.io/reference/collection-model

Because of Opensea data model, you need different contracts for different collections in Opensea 

**As for this question**

> If Minter.sol is upgradeable, how can we apply upgrade to all instances?

Normally, ERC721 is not upgradable.

In current situation, the only way to upgrade is to do it one by one. You can get all existing ERC721 Minter contracts addresses in MinterFactory. and use a loop to call upgrade for all Minter contracts.

some pseudo looks like this:

```
const addresses = await MinterFactoryInstance.getAllMinters();  
Promise.all(addresses=>{
    const contract = await ethers.getContractFactory("Minter");
    await upgrades.upgradeProxy(minterAddress, contract)
})
```

**Comment by rykci** [comment]
@liushmh 
Will there be a problem with future minters? For example, 5 users call `createMinter()`
I use this loop to upgrade all 5 Minters. Afterward, when we create a new Minter.. this new Minter will be the old version.

**Comment by liushmh** [comment]
I don't think so, since new Minter will use new contract code to create instance directly.
